using System.ComponentModel.DataAnnotations;

namespace starter_code.Models
{
    // Represents a message submitted through the contact form
    public class Message
    {
        // Primary key for the message (generated by the database)
        public int Id { get; set; }

        // The sender's full name
        [Required(ErrorMessage = "Name is required")]
        [StringLength(100)]
        public string Name { get; set; } = string.Empty;

        // The sender's email address
        [Required(ErrorMessage = "Email is required")]
        [EmailAddress(ErrorMessage = "Invalid email address")]
        public string Email { get; set; } = string.Empty;

        // Optional phone number
        [Phone(ErrorMessage = "Invalid phone number")]
        public string? Phone { get; set; }

        // The content of the message
        [Required(ErrorMessage = "Message is required")]
        [StringLength(500, MinimumLength = 5,
            ErrorMessage = "Message must be at least 5 characters")]
        public string Content { get; set; } = string.Empty;
    }
}